### ISSUE TITLE
Change code as per the suggestions given by the reviewer

### ISSUE THREAD

**Issue by aksharpatel47** [aksharpatel47/MeMe#3]
The changes to be done are as follows
- [x] #1 Uppercase everytime.
- [x] #2 Refactor Imagepicking
- [x] #4 Save only on successful completion
- [x] #5 Keyboard show hide optimization
- [x] #6 Adjust top and bottom textfields according to the image
- [x] #7 Add placeholder to top and bottom textfields

**Comment by aksharpatel47** [comment]
All the suggestions given by the reviewer have been implemented.
